### ISSUE TITLE
Problème suivi/tache privés apparaissent à l'utilisateur

### ISSUE THREAD

**Issue by Alex33150** [pluginsGLPI/talk#39]
Bonjour,

infra : Glpi 0.85.4 / Cento release 6.7 Final
Suite à la migration du plugin Discussion les suivis/taches privés deviennent visibles aux utilisateurs lambda. Lorsqu'on désactive le pugin les suivis classiques respectent la notion de privé.

Avez un problème similaire ou une solution à me transmettre ?

Merci par avance.

**Comment by Alex33150** [comment]
Personne n'a le même cas de figure ?! est ce un bug ?!
Merci par avance

**Comment by orthagh** [comment]
duplique #33 

Ce sera corrigé dans la release à venir

**Comment by Alex33150** [comment]
Super nouvelle mais applicable sur la 0.85.4 de GLPI ?

**Comment by orthagh** [comment]
oui

**Comment by Alex33150** [comment]
Merci
